### ISSUE TITLE
TypeError: null is not an object (evaluating 'NativeModule.requestPermission')

### ISSUE THREAD

**Issue by redeguzman-gbf** [moaazsidat/react-native-qrcode-scanner#201]
Doesn't work on  RN 0.61.1. Screenshot below.

<img width="476" alt="Screen Shot 2019-10-03 at 5 52 18 PM" src="https://user-images.githubusercontent.com/52161333/66117147-907fd600-e606-11e9-91f4-6718f34cb27b.png">

**Comment by eggybot** [comment]
I have a newer version of `RN0.61.1` as well new version for `react-native-permissions v2.0.0` 

I think it affects with the new version of RN and RNPermissions

**Comment by mertkir** [comment]
When I check my package-lock.json file, I see react-native-qrcode-scanner depends on "react-native-permissions": "^1.1.1" 
This version of react-native-permissions works for react native versions between 0.56.0 - 0.59.10. The react-native-permissions version works for new react native version (> 0.60) is 2.0.0.
I think changing this dependency will work.

**Comment by redeguzman-gbf** [comment]
@eggybot it definitely is. I just resolved my problem by downgrading `react-native-qrcode-scanner` and it's dependencies.

**Comment by dcosmin2003** [comment]
There's a pull request for this one. Waiting for it to be merged.
https://github.com/moaazsidat/react-native-qrcode-scanner/pull/202/commits/1a842ef69eda9b920533a4332bf3ffa0be35ecf5

**Comment by sotirelisc** [comment]
The PR for this should be merged ASAP. :D

**Comment by f0ntana** [comment]
> @eggybot it definitely is. I just resolved my problem by downgrading `react-native-qrcode-scanner` and it's dependencies.

What version ?

**Comment by JimLuschkowski** [comment]
Anyone successfully implement the pull request @dcosmin2003 referenced above?  Post changes, I get this instead of the original error @redeguzman-gbf reported..
![image](https://user-images.githubusercontent.com/37415421/66718960-c1ef6300-edb7-11e9-9bb5-28d282aea4de.png)

**Comment by mertkir** [comment]
> Anyone successfully implement the pull request @dcosmin2003 referenced above? Post changes, I get this instead of the original error @redeguzman-gbf reported..
> ![image](https://user-images.githubusercontent.com/37415421/66718960-c1ef6300-edb7-11e9-9bb5-28d282aea4de.png)

You need to add related permissions to the podfile according to the following url:
https://www.npmjs.com/package/react-native-permissions

As far as I remember adding this two lines is enough
`
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
`

**Comment by JimLuschkowski** [comment]
> > Anyone successfully implement the pull request @dcosmin2003 referenced above? Post changes, I get this instead of the original error @redeguzman-gbf reported..
> > ![image](https://user-images.githubusercontent.com/37415421/66718960-c1ef6300-edb7-11e9-9bb5-28d282aea4de.png)
> 
> You need to add related permissions to the podfile according to the following url:
> https://www.npmjs.com/package/react-native-permissions
> 
> As far as I remember adding this two lines is enough
> `permissions_path = '../node_modules/react-native-permissions/ios'`
> `pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"`

@mertkir - thanks for the reply - I had already added all of the related permissions to the pod file per that link.  I actually copied all of them to start with and was going to trim out the unused ones once I had it working.

**Comment by mertkir** [comment]
Is there a chance that you forgot to run 'pod install' ?
Also I run 'npm install react-native-permissions --save'. I think normally it should not be necessary if you install react-native-qrcode-scanner via npmjs but I manually copy it to the node_modules directory so I needed to add this dependency to the project.
If it still does not work, remove node_modules and pods directories and reinstall them. Also clean XCode project before running.

**Comment by ferdiamg** [comment]
@JimLuschkowski did you get it working? Got exactly the same issue.. Tried to implement #1a842f but then getting `TypeError: undefined is not an object (evaluating '_reactNativePermissions.PERMISSIONS.IOS')`.

I did a pod install, added the `permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"` as stated in react-native-permissions, cleaned the XCode build.

Using
-    "@react-native-community/async-storage": "^1.6.2"
-     "react": "16.9.0"
-     "react-native": "0.61.0"
-     "react-native-camera": "^3.7.2"
-     "react-native-permissions": "^2.0.2"
-     "react-native-qrcode-scanner": "^1.2.3"

**Comment by mertkir** [comment]
@ferdiamg @JimLuschkowski 's original question is related to the pull request which is not merged to the main branch yet. You are using version 1.2.3 of react-native-qrcode-scanner. Instead you should get the code with the pull request and use that version. My comments are related to the code offered by pull request. I successfully managed to run a test app by following the procedures I described in the previous comments.

**Comment by ferdiamg** [comment]
> @ferdiamg @JimLuschkowski 's original question is related to the pull request which is not merged to the main branch yet. You are using version 1.2.3 of react-native-qrcode-scanner. Instead you should get the code with the pull request and use that version. My comments are related to the code offered by pull request. I successfully managed to run a test app by following the procedures I described in the previous comments.

Yeah I am using the updated index.js from the Pull Request just like you and also adjusted the package.json in react-native-permissions to ^2.0.0. Still the same issue somehow..

**Comment by JimLuschkowski** [comment]
@ferdiamg I'm still having the same issue... I've performed all of the steps in this thread, several times in multiple permutations, without any measurable impact.  

The index.js and package.json in my node_modules/react-native-qrcode-scanner folder match the pull request.  My local package.json references react-native-qrcode-scanner 1.2.3, and react-native-permissions 2.0.0.  I deleted ios/builds and ran "pod install".  Any other suggestions?

**Comment by MASAKASUNO1** [comment]
i have the same issue

**Comment by f0ntana** [comment]
i move and use react-native-camera, by default has qrcode reader.

**Comment by aimawari** [comment]
@JimLuschkowski Try remove node_modules/ and package-lock.json then `npm install`

After that go look inside node_modules/react-native-permissions/, recheck package.json inside that folder is it match to `react-native-permissions@2.0.0`. 

Sometimes npm is install wrong version, if in that case you need to `npm install --save react-native-permissions@2.0.0` manually.

**Comment by helloravi** [comment]
It worked for me - 
1. Used the pull request
2. Installed the Pod

https://github.com/moaazsidat/react-native-qrcode-scanner/commit/1a842ef69eda9b920533a4332bf3ffa0be35ecf5

**Comment by reddeguzman** [comment]
> Anyone successfully implement the pull request @dcosmin2003 referenced above? Post changes, I get this instead of the original error @redeguzman-gbf reported..
> ![image](https://user-images.githubusercontent.com/37415421/66718960-c1ef6300-edb7-11e9-9bb5-28d282aea4de.png)

@JimLuschkowski,

`react-native-permissions` is not linked correctly.

**< RN 0.59**

run `$ react-native link react-native-permissions` should solve that issue

**> RN 0.60**

Linking should be automated if the package can be autolinked

A lot of issues can be generated depending what versions of RN and third party packages you are using so I think the best way to link module is via manual linking. See manual linking docs [here](https://facebook.github.io/react-native/docs/linking-libraries-ios).

**Comment by JimLuschkowski** [comment]
@reddeguzman and anyone else who offer assistance, it is greatly appreciated.  I tried them all (and more) without success, so I decided to drop back to just using react-native-camera as @f0ntana suggested.  react-native-scanner-mask is a nice add if anyone else goes this route.

**Comment by eggybot** [comment]
@reddeguzman will this not work on `RN Permission v2.0.3`?

**Comment by afilp** [comment]
moaazsidat Can you please merge the pull request?

**Comment by abiespinal04** [comment]
I tried all the steps above and it still results in an error. I hope the merge happens soon.

**Comment by abiespinal04** [comment]
I tried these steps as a temporary solution until their merge the PR fixing this issue:
1. yarn add moaazsidat/react-native-qrcode-scanner#refs/pull/202/head
2. Add to your Podfile -> 
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
3. Make sure you have your permission key in your info.plist example: <key>NSCameraUsageDescription</key>
<string>You give permission to open your photo library?</string>
https://github.com/react-native-community/react-native-permissions
follow these steps here in case you get an invalid 'RNPermission X. Should be one of: () error'.
4. Clean your pods in the ios folder rm -rf Pods/, yarn start --reset-cache, clean your XCode build and uninstall your app in your simulator. Then run your app and it should work, at least that worked for me.

**Comment by Amirh24** [comment]
Any solution for this one the does not including using POD? I use Carthage instead. Nothing works for me, I get the same error.
Thanks

**Comment by markl-vesper** [comment]
Has anyone found iOS builds failing after adding the PR and the lines to the pod etc?

xcode build error as per below: 

duplicate symbol '_OBJC_CLASS_$_RNPermissionHandlerCamera' in:
    /Users/build.mac/Library/Developer/Xcode/DerivedData/CortexMonitoring-ddckgtmysivxhiebtkcjrvtlhtos/Build/Products/Debug-iphoneos/Permission-Camera/libPermission-Camera.a(RNPermissionHandlerCamera.o)
    /Users/build.mac/Library/Developer/Xcode/DerivedData/CortexMonitoring-ddckgtmysivxhiebtkcjrvtlhtos/Build/Products/Debug-iphoneos/ReactNativePermissions/libReactNativePermissions.a(RNPermissionHandlerCamera.o)
duplicate symbol '_OBJC_METACLASS_$_RNPermissionHandlerCamera' in:
    /Users/build.mac/Library/Developer/Xcode/DerivedData/CortexMonitoring-ddckgtmysivxhiebtkcjrvtlhtos/Build/Products/Debug-iphoneos/Permission-Camera/libPermission-Camera.a(RNPermissionHandlerCamera.o)
    /Users/build.mac/Library/Developer/Xcode/DerivedData/CortexMonitoring-ddckgtmysivxhiebtkcjrvtlhtos/Build/Products/Debug-iphoneos/ReactNativePermissions/libReactNativePermissions.a(RNPermissionHandlerCamera.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It looks like the project tries to bring in the same symbol due to the references in pod file to permissions from
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
&&
pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

If I roll back the changes to podfile then I end up back with the TypeError: null is not an object (evaluating 'NativeModule.requestPermission') issue

**Comment by renatobenks** [comment]
I'll be closing this one once it was a problem related to the `react-native-permissions` compatibility which it's not happening anymore

**Comment by renatobenks** [comment]
and just to clarify the comment made above by @f0ntana, the `react-native-camera` don't have any QRcode scanner, it scans just barcodes and nothing more beyond that, which by the way we're working to move it as a scanner on `react-native-camera` and it will be available in the next few months, feel free everyone to task

**Comment by dalugoda** [comment]
This issue is still exists

**Comment by renatobenks** [comment]
can you detail better the problem that you're still facing @dalugoda?

**Comment by renatobenks** [comment]
@dalugoda try to see if something like that works for you https://github.com/moaazsidat/react-native-qrcode-scanner/issues/289#issuecomment-690045328
